---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- if .Values.maintenance.customResourceDefinitions.maintain }}
    webhook.stackable.tech/conversion: enabled
    {{- end }}
    {{- include "operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: conversion-webhook
      protocol: TCP
      port: 8443
      targetPort: 8443
