version: 0.1.0
spec:
  units:
    - unit: &unitUrl
        name: "url"
        regex: "^((https?|ftp|file)://)?[-a-zA-Z0-9+&@#}/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]"
        examples:
          - "https://www.stackable.de/blog/"
    - unit: &unitPort
        name: "port"
        regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"

properties:
  - property: &opaPort
      propertyNames:
        - name: "port"
          kind:
            type: "cli"
      datatype:
        type: "integer"
        min: "1024"
        max: "65535"
        unit: *unitPort
      defaultValues:
        - fromVersion: "0.0.0"
          value: "8081"
      roles:
        - name: "server"
          required: true
      asOfVersion: "0.0.0"
      description: "Start the OPA server on a different port (default: 8081)"

  - property: &opaRegoRuleReference
      propertyNames:
        - name: "regoRuleReference"
          kind:
            type: "file"
            file: "config.yaml"
      datatype:
        type: "string"
        unit: *unitUrl
      roles:
        - name: "server"
          required: true
      asOfVersion: "0.0.0"
      description: "The url of the RegoRule server"